services:
  camoufox:
    image: camoufox:latest
    container_name: camoufox-2
    hostname: camoufox
    restart: unless-stopped

    shm_size: "1gb"

    ports:
      - "5902:5903"
      - "8002:8000"

    networks:
      camoufox_net:
        ipv4_address: 172.30.0.12

    # ОТКЛЮЧАЕМ IPv6 ТОЛЬКО В ЭТОМ КОНТЕЙНЕРЕ
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"
      net.ipv6.conf.lo.disable_ipv6: "1"

    # DNS только IPv4
    dns:
      - 1.1.1.1
      - 8.8.8.8


    volumes:
      - /home/docker/camoufox/start.sh:/start.sh:ro
      - /home/docker/camoufox/persistent-session:/data/persistent-session
      - /home/docker/camoufox/profiles:/data/profiles
      - /home/docker/camoufox/scripts:/data/scripts
      - /home/docker/camoufox/workspace:/data/workspace
      - /home/docker/camoufox/log:/data/log

    environment:
      DISPLAY: ":3"
      USER: root
      VNC_DISPLAY: "3"
      VNC_GEOMETRY: "1920x1080"
      VNC_DEPTH: "24"
      VNC_PASSWORD: "VNC_PASSWORD"

      # ---- SOCKS config ----
      SOCKS_LISTEN: "127.0.0.1:1080"

      # upstream SOCKS (можно менять БЕЗ rebuild)
      SOCKS_UPSTREAM: ""  
      # пример:
      # socks5://login:password@1.2.3.4:1080

      CAMOUFOX_PROFILES_DIR: /data/profiles
      CAMOUFOX_SESSIONS_DIR: /data/persistent-session
      WORKSPACE: /data/workspace

      # DNS поведение (уменьшает странности с AAAA)
      RES_OPTIONS: "single-request-reopen"

    tty: true


networks:
  camoufox_net:
    external: true
    name: camoufox_net

